<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SupportPortal.Contracts\SupportPortal.Contracts.csproj" />
    <None Include="..\..\specs\001-support-portal-rbac\contracts\support-portal-api.yaml" Link="support-portal-api.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\specs\002-branding-smtp-notifications\contracts\branding-email-api.yaml" Link="branding-email-api.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\specs\003-global-admin-settings\contracts\global-admin-settings-api.yaml" Link="global-admin-settings-api.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>